apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: btp-app
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9216"
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.42.0
          args:
            - '--mongodb.uri=mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb:27017/admin?authSource=admin'
            - '--collect-all'
            - '--compatible-mode'
          ports:
            - containerPort: 9216
              name: metrics
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: btp-app
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
    - port: 9216
      targetPort: 9216
      name: metrics