apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-service
  namespace: btp-app
  labels:
    app: plan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plan-service
  template:
    metadata:
      labels:
        app: plan-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      serviceAccountName: plan-service-sa
      automountServiceAccountToken: false
      containers:
        - name: plan-service
          image: btp-plan:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082

          envFrom:
            - configMapRef:
                name: plan-service-config
            - secretRef:
                name: plan-service-secret

          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DATABASE)?authSource=$(MONGODB_AUTHSOURCE)"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

          volumeMounts:
            - name: plan-uploads
              mountPath: /app/uploads

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: plan-uploads
          persistentVolumeClaim:
            claimName: plan-uploads-pvc