---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plan-service-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGODB_PASSWORD: AgAtEetfp4h4oa2T/uYbsVqO4LeelM4q2bijsHmG2sWBnp7Lns/HHHaVcPc4u0lv0Qp5gyZGaQgDqNA1BlZ9ZB8Y8W/AgvY7OR6sIw3t1TzUaGRHHkfIufp6+Q+UWQgTtESHDf/TJBIoTEbwh9C/+DLxijsbqraRBJOaSNhbIHyL16oBZvWvw1pNLiLSV+ol2zscwR2bKgnI3ssvpD6dxkDuBe4jd9UC3eSuEDOjCbytgxAYhlza/xIGaUp9SkJ/Q3TqjK19xI4BOntLfMzeTFHf/bWbcf0lE2Ck+v68RGDl4Zia5aziemW2CVDnFx4rdXwK/o4v4qirAnKBgsBs96mtnIfqp1mDL1M5thzcIOUCzIeJv84WQOy/G8Kr9S47q025m0y1hcJt+pOZOgDtrJdeWquQNywL4ewro5esShxSUoY94VCj+32l4ii8J0hAUPxZU9x9bd205NckZNKm81baXRxK+8gdDHHSe/pWTiGqa34d2ejHMfclpUqyrydWW5PNi5qTavATvaKSo+xaIejkL/kb2EuhZTM/dpbxpVk/0WfjwYP1gnPaFBXRHQ47NMlErjfdy7Jm9+iPMkt7VgLo/AMm4QmJjIKNje5za4noCQzA4A6yh7piiyloFlrQ2Vnnv4/t8t1ZJmoJPcxempH+M86jYGoPKHbHVVktNc8mT0M1KKuThkAKaI07VQwFntsjNnwuTzz75BctScdhXeiOB/r8TKiBhXI=
    MONGODB_USERNAME: AgBuCwajSzbHM5cWY/Y1rDjKQsy5BucC55L/5QsNfPHx1u4ePVesajg7p4oI5Xt+SvJyiZPj3Cb1KbK0/zLimZZbgp57iHgjghS8KRi2U6ZdRfsZWVFsqKsU7kPBsi/IzE7kJJ5XNT9HyalRBTUA3iVpXPvyAT4nwohbBYKBxFZEPNBdCCcGKbNhFjeUpUVVv72eCKruKR31cA9Aa7sk0Ffjx+f5cZnqZwEFzZOLg2bEKBxef24SBhu5Bkoqzy+mlCFMYFUScbqaZ2MvgBCHH3rb5A8v6zUJjIlOLit7AM9eCE1P1gW/8ZWHu8iDkbrar+pAJirazOpsykX/vMmNj7WRdITxEIS7PTGGY2Tkx8aDP0lnv4gS5AJJff+rzrLTlvaGzowG+ZvSK2byEu+CqyonKGp8W7T+xqZvdZWYeeAPQwS2Z6UnGEacjV6r0jY0fsdbOV+mJuIykb4LVF6M36DCaWyyy5j3BV+7D6cw+JYnzCwuY2x1TivIgfLqqTXVXrJ2L/R1UkwdeiJPd4GfUznFPDJWipfiQwkQecr5q7ylXw3Bvy7KCDHJiA49f0oeKdf9W0cFoKGafpxuQOhiFQh7yxcjePres7YDlQvPbpPsFISaoBwfvMNOpydKWWRCVB0rSrbbanRNt/9yqYL6c2+1CRHq1PBf2PEUJdbHtQ4NVDFEVzTIXpVwWyKC3dHjliaRDbKS+g==
  template:
    metadata:
      name: plan-service-secret
      namespace: btp-app
    type: Opaque
