---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCAMbbL8Z3gx7xFN/3k+Pq60CBRK/YOcGeEmLmICSaydnC2JNP6qrl37rEGGjrfwv5hSpoOHLhG6B/A/1TOuDu8N9YvbWz3o02Lmi4DCVopeosKpFgjWJjBXGR6V3jz3Aw1S5GC+IXo2gigTLTRnMW69qXrkVTdkRLLke352akGJcvbhG4FUDEcFhwCJTEGMLVk7j+TxQl75B+OPXwGaP4MFrfBsg0vA75OWGECaMyXl7WbS/8LJDXHt/C49ihdlkP5YJeijundj7w8rtRRKdbHTiMH8QQZlQTyrp1X2iBh0KOKLEhQNCq12it4sk2++byGBTyqZc7XT+YQv6ZLUiZSxAjAu56pK5jmhVRG/kV92TuTy6xGWGO5EAY+k3djP54XzQlrqDzy2bhmoKbXZrabKAzglN2lILHJwnfDkFabhyjH4xeIwKB8J6Hq6TCFOQya6C0Ml+BK/jjLuBF5Qi7pH+6a+deV32+oQQ+zJmU2oD8gE9Tnx4LOUz0QOm91mT+zUYbYFnBqY5yAT1vb+OqTEjrdi+2dV6cqKEgDAPE8a/1/G84PiSDJZYHHmsH19yDas0IbF48p+JIYzbZ5/O6ndw8JKmowmpPm/66Y5eooarfYVwZImCUjCGjuPqPR4PhniZ66T0xsGwvd/0cZkXfk8IqS1gCpRTIKfH9L07XTo06qK+JZyYFsQiRDxWDTZqsnX8pv1q0nOxoFmQqCwM0r2LTpYtbyZMk=
    MONGO_INITDB_ROOT_USERNAME: AgAObxomubzBcoTs/HuF+XyTsUF6DCcZtbMtKQbjo7PqEAocJXNfx8vYGJOEszppd8zoRVJoNOLHM1eT0E/WRm49yha4B9Ff8Zf8u4AUaGuOCb3wPeJpQli6HSaX37nyEexJVdlhdxEcJYnThqJTsxu6QXEK64b21KKuoH4wS2od/43vUygtjz3SarQggKqz+cJCg0aDPr8ji0w/BaKVcFE+ZBL1JRwtf7AL/uKwgBT4dVP1OMDQTavmvD1Zi84Ir/cGEG/uvb9Jsggw6NrEJV8XDIYsh/x0mWRkI0IKLMi03aCuN82cwnv6YlosQGynCdleYUh5mmFkcLBIa7f9eW9l9lXRW5p2ZnGMUx0q+mz9jfhHZ916HHj9Zf+2r4/zXmyIxf4Kr5M2m84sZLAbBgL/6pjvNI4WdFK5UPcjTzSw+FZPY3yPOI4I1Y/Rb5NQWE5T3B+URECNIDpmbXMCcCRuI//gL/dwti5lkzcoJvv4ERYj1c1O0XGL/1ohqEJ4J6VcShfQSwolyH+BTHcKyc/w/mtznsjk3O5Dgg6jvroTQ3Rfthjvoiqlb4yfdax5LyryDbooRd4SUOVOxzj2Kw67Dsz8GzjmXXlob7JQGWaSn+6YEId6iq+d/4a9Sb+eOVgbwxEKNx6v7Nuk0fGE6kLt2XxxmDwcBpJ1Ch6epg8FLElAMKXFvfIu/mLaSd45Jv0/7WC/Jw==
  template:
    metadata:
      name: mongodb-secret
      namespace: btp-app
    type: Opaque
