apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: btp-app
data:
  SPRING_DATA_MONGODB_URI: mongodb://admin:btppassword@mongodb:27017/btp_user?authSource=admin
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/