---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGODB_PASSWORD: AgAJiR4sAi7xB/VjWmRA1TpfKNvenp8rio6dbeXRwScIvNBkyP2UE0n0YcMaiVCneY86A5BskkSJjUuu2VxkSrEH1ExpS+17l+ATPK0o+ZThNuyMFaFwRHt+oblfIag5SSsdtYLndfjRtBNcOMXsXsP2MZzTdH58NHHq9TQ8a1AGF6DQlzC/9osCMpSkRuZwgnq40v4C2ZhQ8ACZFyXSp06CtNnrlCMBdfVVO/+r9k992lPpXWDkJFWB5Tz4X44a+7wrDmdu+OkTUvzx8UFgR+EmP2uUR2bv32iKNq/Tm7KYRlUIoo80qYIOHWvjNKMsz4kfSRNVfLLuyzcvKZi+lnm0Uzb1X4eNvXSmB2McppW22/Q8Czya/nM9gnXFfCStb7+Zx6CJ4qiepH/1HQJgoGTIis4evLzQqtYySorNclWGXMXo+BsfevQXJblf/kdrt0M0pUZmWLTJtyIP+6dnChXRSg6PqNKNyuzOOC1WdkAleUUU+859XI7Pqjy9eS4ekzPJvS8U7xKU1rMZCNSVTKUh8EF+m7gx/Aj+KCsG/pE0CVmdJS3hbL+KTlCqI22aA2yUL9THRukVWJDEkcls3crC09WrsBAwaT6N9QraEY68z7zC34gr3z110LKFSAjvVySoBpUvlKtms30nvm3+vkBKyFKjx5lAxWsmhzZVIeDL92E9k1PM5C466wn/4JgZ5nxzXPAnKObLo7yGX6+wIc1Uiqm0xiFCov4=
    MONGODB_USERNAME: AgABV3202BB0wuK22hr7AEKQMMoDifJBQQPy/PomS6d52TiL7HbTeS+lolamDmmzu8i/l+VZVCQJIYa/58ZMG1YnNk1bItz6mcL1rhZ6cdP6KRuj6woMjhIlE7h26km96GzMKdj71IIPQTQbAbeEcqFGf7X3I6b3gzANDHV4o3zlyHVUl58jfRt39xSGPyAEGJU/Kkrp05sYTuIfbGxhIPCVW1VdOUvcunZtJzD48zaRjplCkoDDR0tnT6lIiXArDf764DOz6+tSuqVrDVhcjWHTDxyacdEQBsl4CHyUGZ6nlZSHgyYFB7S5fjVTvDuHwwMAHRRyKiRrnzN62zRUqPK6pFqlRSjYaRpcQuvPNgAuGGGQ5IzJivIc9vQXPg653YNJSnVqUmQrOmvjAGUjEYxGZxOzizUtqp5jrsCYwzDw/yC3BWx3b2IYTYQPDOST4srdFDpWMb7ec4MLEU8Mdy18U6g7FUeiParM+a/iFVPJ7Mob98kRwQtUpCVqXcspduUWzLH4FAvU4C3TXGVqwNGn8RJUoqSSB//LCnsQtSmKLI6sPWuHiyDPlJIkmSroOnQh6B9qZEtjKpCRmmTq1dsmksHGEQyIi8V1xktBPLZqkIRU8eREuqQRkotG8R3hhhNb3pJHFeiW4uVNBA3FHLl5smypFnBpD0zpM+zEH/22Bh38Njn+gCdo2iTazimhwXuoUZlboQ==
  template:
    metadata:
      name: user-service-secret
      namespace: btp-app
    type: Opaque
