---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: btp-app
spec:
  encryptedData:
    password: AgBa1jPzin/Lqc+IQ+QIifcXm3mTV/6AiDqNAtVozOFQ3j/qjzWNvAFrkULAnY3/+GA2OMZwGU40g07xAt9zMpZgdRBWfEhV3BwEmgh8Hv3LEsQSBqzkFbDUnJM3wuMCMWMS5mWRMSxcT2uSfj+bk491sz8ducNTCoM/p+1u4O92D6R/4RaSCb1DvdQu+nEHUgu6zJksPZjx93eVZzsoYcojFBYO2sCRefWUnCnafIaua6WRHQIg+oxBTYjJ6rLmHPoOeoiNn+KnTkCgQb14TveVHbiAVIo1a5tUG4cyMq3umxV+M9emauOR7XvpKZefRUPY6zgwOMcK14zZIYh+xfT6VGIgKCGzY+h8oJWANrHDwg8LS0QaC0jOFztg9PoRypR7qcwLV4GAX31rbjuem7h+zJ6qDq0A9bLKYmMQnxDayfG4obiblB8TAWxHdHJOkuOcDec1GHkFR42Aj6lntuzE3kUKZTE30FQoN2IB+bC6cFsJ/ln7omQ6oE44mZebkjBFVzoZIPFYoTAUmGxs5SeQzjLC3t1ct/z70uBGM2PXdWcOxtq382R3K4A/pzcGmIJW8A9RnfM9tExtSSKrLVQIO0GP9/t2My/7Vsnom1ingum66ticyaFh7jJnHVSwC5r3K/xwVx5B9QyPMv5sAgvWuPdIcrAS+MNkp5H9B6Tz6obRxulNvyX3Fcwp04bzYGRoul43xaLVu1ntLroG34DkCjuaxfcF8Rg=
    username: AgCnQKNqFruiHKXBwatmFIJuhSDUkHWl/9DLBmBYBeR9WNLvVStX8dZ75MMDUVZQ8L4je6d9hEi1+Hyrg8IY5kQ/5au9layF33U/Vaz9nU6xqPywb0N2phB79v26elSkBEUc3kRej02zml11QjrO0axm+yqJS+LjBNEXox71KV3qXX0xFanAoIS3H6TD2EI5tRb/bV6KoCKrqk+uYDs5f1mBzbKQqCYAivzch9wdDAzcYiS1oBPcY2JIQ2w7uEO/GFVKYg+juM5tZ4mG9B4PhDYBcBr2XyGEM4Sm/7HRnKuTg3gvS9JavuULrShrWm2UMhkg6Di8sHauHr0yOWYOBrJBFnZHalx9xuigrp4iGdiY40EVoZ2CtmixXy5woTyZWwE8Ab2EtnEuMPWwmfDyCv7UnfQXEbw07b24s5k8X5fJB6LIgpon0jFIPTlaDpsNw8M3HyaWtoEQekpw/wGEzuieMHy2mE1K208kpXGiw6/AHXyiOlAsn/Jl5mS2+fUjPInDmCM+PFpB1aUBmbcTFxtKRpgSQkaWFRG/WY99pn16lUgZgM8tvDZ1wKaIkd7AlG5UA1SDRb04IZ99FUH1tAgIpByMuMxWGS2nTwEiMfeJlSzQxHCaCfTiKlsZSOf+xLvRUwEwpiKypUYNRyXSK+E/2DwnF+g9ejWlzjqBKIOZ0IpYHoKaV9ETwxc1NMtASCdaMiE=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: btp-app
    type: Opaque
