---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anthropic-secret
  namespace: btp-app
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgCI3OnxdfE6uXw4TPaBvSzNfxMQfSzJC6HNSsJwmoJDiq0yzZi+ae6pEgv3h8OwviSpJRGHRtq1yHAC0kbMTHwUi48uZ4E/kC4fY9nOvPQiBlXCuueX/Nr4K0g+FO7VlWPj09BcQ5rzq2twmo1YpV2HiG3ZiBUIZSNZxKJmWURnJpVBlJfEOYh+YKd93sDQZabA+rfFWa9ZrF9TA+WSno5VprGmagLCpx/5DKCDKiB7TC7VHNVvozgiqP4gcQMx/1nPe/HOtjST2NTqVSP0CZtjSBe94w2iqtAc80Em1aXM56haY3LkDPhIdrZj3O18/Whf2FG7oT1dutqubU264U011ytvlvRKcrrgbuId/Vht/g4IfBeKMvjjTQoGdz1bH4a6HxVKGr30GnHYhdV9dVwfl+IhjlYffU6FkeE/PA2Gu52CGIPPPbfU8o0jjHbwWe4+vH+mmCLmRAWNGFOsyTQPoCMtgKxIgpYr033Cp0uXNzIbEnM2xfuBlNOuGsFl7EmLjSqYa4TBctONdgWSLB86Ik0JvUR+Xj+qUTDruMKl+JwvDrJuksxCZd/+6rb/ZGgUrD018eyxhc2xsQ8Kcww1dkZcwyhoqpeIGZabu3+EboG9OS12dw1cNjAE+Kno36lCVuGdCbRkEueY6suey9kDYvFr84iISZUTrcttInocEMU+0FzdkKuArXxg7CCX4MlYQCDOfbihDXqolTRQr48aQsg4GzGcoNkJdh6VdsxTADRciy8WVuxBuTW4Di/2FYAXDepfja+sjfXpdcW0DoQ8udeNL2rou7HKjPnwmSyuOeIx9JogxU6tZ0XHqFcHw9lglPSsqFNIUlUtgeQ=
  template:
    metadata:
      name: anthropic-secret
      namespace: btp-app
