---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGODB_PASSWORD: AgB38QhJ6ig1fpf8e7fzVhClxE79KycLDDJFnJLvkgJqFulUQac/FkIWaXLa9NmQgOnMkj0kXUEZd+T/1IrqDd6ft+gfOEbnyFF9zwJyjkVpMCNKHDE9e7p6f/JJBKeGZsR8m8gh0dLJFz5j5uV9k/z2LePTsuuCGB1wwWSQ6Q9ypRsFuLQGloWjfhGoa4OdpKBKCIXpT+EDs8MlxqPypBA+f4+z2B0dBI5vy5VxSw1PYLeNwKNWDIBdVI4lMrVVhQ4FI66dxKEWGtdLqqftnbXsgkb/76FABgjnbKGpmDjLv5gcziqVFC9EFwXzoxELu6IHnFDWzao1V898xgXGDTQu1dhBjSohGWup/0sbNrIYEbjmI6k3xr7S799RwWuZ8+5xkGB6zQ3OIyMPVN6mLuPrdT/HGdG/2u63fJlZBJjEI+bP2F2pwRoPC578YGyK5AxALVgh0JHnK7+IuCZY54+i+44tAKkQatoWTHSE9/GaRblJtVfincHiYt5kGpRKZJapsQQSTn0r1go6j+E9/Seh47Kl3YlObBY/pSX9uC+s9fULjORdlTLh4L59m2nV0rmDJtkJqUm2H/QCB0dUUqq0D1FxxTZvkPUmelUjMgZx4rjf/LKLfW3jolRk6EEwmkSoZmRt4gnItLcx3rzewNaijHoEDLtqJLlwzVpCVG+PE+aIAvQf0JbxZ8fu/ff0SL8RQE7ldVcmFVQ7Eo/bceAzcgqvhtoxDhE=
    MONGODB_USERNAME: AgCm99SWdCn0AalPRsdRQV2KWWW5Qz+pQTHlzSoZWoCfHY+g/V6t2O91vQojwTOb4b0EVo5s+/5AftYcwbJqGW5I0tg/udKxAY7ve1vWdv9gx4Xqms1A7I2v53eat7zFItIvfeS7qwT8xG3Ca+6pbohjVJpbGeIMtK5OOBgLonq+HNHb99PsUg3X1osLqsP8IxUwP/fvpKahpta3wgD1Ke/k4cTzru1Y+V2WrT+2JiCvuoRZixXE/aWDI1NmDBbxwrWm5jTGUjQj/khI/P2allMWl9mQqsRPkwRxyRN4BxjngExkycGLQsRM5UU2iD1DwSyU+L80QIFWgZgaceBosx9rAyqByYTnA0VoR/kV7/NZqICdPzBYY//FB9R+Cqxg33pM0c/ZM3Rs+jVkzsbpqi2I9VJeTILa+41aAoz+IWb7HVX4Z7+M7CKdAqufnDPUoUsVdNzy+sM8q7giOGgs4mjwYMMc3wTKZgM6Q9or8HM2MsQD2bTeKNyqmm3WeeDmolkEUn5UogO1V9dBVD7W/YnBcoRuPK7D7bQe4yNdD4kajSTKKSUWk6TFaDK21SEFTHCbHBxHTJoGw/vvKCA1gTO+rzJta4kx0xOBAL2wcmMHZRl3PX4rqPYAe5LyZ5PGyr8uz3f62IELaeWNmS25OD54KF4PhsiGpVhQYKHcC8eu6ZtH8E6E36q54rb6EYLmckCblz/kaw==
  template:
    metadata:
      name: user-service-secret
      namespace: btp-app
