---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAn6ox8Qi9CzineIfBvPxt/N26GgVaJ3VxbA3FyvFuR1fWqKwFCDsBfFAMmrTp2zDmZBwwnRYHRv1mYFt56+3jK+WTFEMvdwcI0V0BK4yv84x0Q2QS+gCvWm3CRD4ENmsG8r1+VQaRcnyVEMZnI8yBEUNcTLiXXlnQJMq3tDJYL5P0EzUDcEaN6KNUKIdkc6NAODB8YGoquWXOYAZG/8fFsDo+6YHak1J0xlXiZK5+TDSurKdStiRgo7ZbAT4oPYIsy+4/2URuJbS1nr0zZ5i6LwEHM3I5yZznxf2bWNupqgYboGb7sGVytUNCWxo1Km7yZ5TXJ5X202hz+Jqp4xua6o/dWQ4cTqjZNQxGom7jvsfrsRCevwqZ4yCk2n9tYhpjc/6PWpFQEwrehO03HXhmya4wEVjgLRUz/2cMiyPD3ZL80EPyQ9ffI9DpJmfBLuYYH8VFbvHb2I3YtS2kKzgW2SiaE9X8YuSMYB7NKUR2ML9IqNFceVB8VtL+1Uat1nkflXG0ZX/nlskMkIWaKdSQI2Horzu9pTAoybuLh0igdoJ45O8kuEaw9OBT4DgRxZnCmxaya964YtKOjRhswjbSOmdBQ9fzQKvpaRVi3AmWoTvIwvWIYsRg52hdDll/qC1jkj7P9F1rJszhVhlagGGtuKI2iweAhApbMxQRunbf8dAmglQ8asRPyB9RSHvXi/OAEgUXfWpn/YXB/BB69kvh8ilunVdn17rI=
    MONGO_INITDB_ROOT_USERNAME: AgAUatKN91/MaLlZS3BvIMUDaRRYZeaNIgBoUfw7utYw0NnXHn2mFrtO8yu/E67rQYqXMXSvF6CSIfzlDFtyp5EJbz5ULT8Lk3MwRQhHIbFO1YQ6ycWlDlO9rGMoc77LOGWqvUCvHwHiLilWQ3sJpGBbkHm8oeJBFWcKryWD5I9DMEXdMW8r4g1wm/IPX56V3BegS9lk97X1DtomjUjqUKeFtmZ560GXqX3xNbeB1wgIAw2CbyXYSG7VFBEFzsRPvsohNJ291NP4M7GGaIeJW8KxHUEGQuQJV1uTIhA6JIVvlrOdrc+bjuWars0ESL+geapKJbU9RxM/UJrTulA3muURT0pCerl1g9MeRAyYyGhq4rPw00jAbb5LBDm8YawCHVbqFGB1tda9Vb45NcVePc9d1m4Jj9dxNlVgL89duTop8hSldkKjQtpWpEgMz9Yy55A3B0Gj3ZfPUG4wwArBlC/AGeeE5y+4MBZTOYvL4qrK7hQ5HKMAey1B2I0PIG9dhA1017tCVvxc1zrbDD/+hBMXUZI7W+G6/7OGEyms1oVAZcnG7Hz7isWEI73FLa2QlV/vj1HXHMf5AA3a+y0OiPzSV1KrRQnVJF1RCGhQhfLEApgebgGFwIDC8bRnNkjZJtv2jXFyfCVGDK2aQ95bTMTSBPZnsOG31PLPPwM8sx9qGX6OFY2zA/WBhdyQ5NCRTRRNCnCuwg==
  template:
    metadata:
      name: mongodb-secret
      namespace: btp-app
