---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: btp-app
spec:
  encryptedData:
    JWT_SECRET: AgBfKQK3iq9aijM5YUA/q8mqJC/MmDbGW6cfG2L+YA1MX7DKH2dJ8YFyK0lNtcMTO1tS08dhQwaWdjq06saEDtcDbI3PuP0gzA7WBVCiQMn5J5W7T384g7hrt+i7kX0KzAQnSNslwwgwSohujFxTRm3yd7ly2ZvGl0wn/62LcomXfBjKYdcgbZbjhswF44wyyg1L8PiemkqXx7zq/UBymR+wBm5A0omyZDqh/9HF6D5DVTOfmlkbhW0fmVJKqEu3Ft36xALNUXmaURYyy63eI62b2uVphHyfAQSirzlx0BPGyfCJeHT07ahd86vHv+9qnWnUmZVflh0scArAj3d0Kn9MUVqBgC5tGjCf8fUc7OW3QqstBcKBjCAafru+PXbBBIldDlBqwl21gQxCo20+aZ5vRJLeZMZ6Bx0WAO1y/qT02uXTRVsNpiuUQ1QcGJLDj1D33mktTd8wsu28jlaTFHzPcATerinsFOYw2rbgi4qW8ycXQ4CEF5NKRQUYTas9XK+h0XNoLfJvmz7IoBX+3Eaq3tTiMs1E3BSFHkaaJslvh8zPWfEicXnOOhNdNV8z1CKTCjiLTJRAcnHeC2EboK7Y/94aSM11e2qGsDBZBH1HeAC4rPdNsmWkzQVFM7Elg8ILj2/NyhtHP7U+urdHHCnduxSndR60CGC4Hf/DplrycmrvVWHzHLuAf9t5dkJv2E35mJHKZYoTsDbMu40vZkPM24UnpB8O8XV3Iw6BCqrBIj3QC0DpgFOjycumeC33XONi0AKswt+kjrZVg/FUYvDNZ25VL0C8GiiU
  template:
    metadata:
      name: jwt-secret
      namespace: btp-app
