---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: btp-app
spec:
  encryptedData:
    password: AgBV+SaSs+OD7E7lAvCGc0hvZRULDJmho8E+ktCD/hELDF+B4LNIZDeey7NGgdnh+rJ9oVVjcGoi9wfC6m7Z3jg0Mq/vMCo786ePUiuBrXw+hgEmI+T7LvTCVif5JfEQ2iONh+JFG7xaaGShAZmLQHRlUQpL/8zV0rzPLDdjauAEl6Azh9cXp6XyJ7fLuww06FgH01onlsGbrqY+44FQzqdZ0vg8OVxUYeFycQ05h9Z9ixdqoNF5IHXZrHcileGbp/xS6iJwuOe8H3Zi6ENXDkbv8BAmutN8AZYRgVKDKmDanOPrGGdCBQAJiB1alioyaaHgeVmnRZ6LqXhTYiTmaCbdYn996GYaQQFtwtfDwLrQ7RTnR51tV0RSSfI816NMrc1CFXJgYwsOBj5PDiE9uom+YuImjsyC0B6W5naqy+8V3tSxB6XW6b3+fpuy2Mpt0fhRBp4pX7cVvfgsXhITqlgI8fUUgnMG3EJmCFeBccgbrMXwNsq6GhrON4AbJad2GRl7QomcYlDmGaI5Z1hbuEWst/FG9Upyr0aIRYIO3ZEJ0WJnnNseSZeH0ACM6RNgJa941t20qoHE+AE39Xn0X4zhHoqqgclJIOWIJ3rrMPcJSyJoKwRVdOMJQMvIvI4Ov5HOCRmJGNH+d2HMT98gR2cy0vaOg5gPQM3pU9s3VbJ5cMpqUQOcitYPptQDy1U/He0j7r6sTDMj1F7teE7xTgb1pCD9DV6dFq4=
    username: AgBtwvzV2GvbYvFncitnBqkoDD7kwy7keKLQEsL1Nn+a+u+zLBtj5jQQDgkNnu/O/QVSTLRZg9Q8gAdAvT4ggSImO/BikBjzC6znPNIKXXw+n2mNwA3hcwKNT/zLP+vWd7p5aC055lej4JnzroJPVX2FF+r4cPvSZQoB+8pVslGa/cK7cvK7gk+zKbll6GSkqt7igWLSyu9Xmgg+auSSQIwjWhtDH4TyQjZ2BkLCLVo7fcAk38dq1L/fOwEWXZIBBM+iDT+TewRAFZ28CVpUsfkBR91mCT2SEt1gsuKwJWROPnVR1VmD1tWAp/Zw1+3knUXXW+mdwkf0rtuuuxr/SOqpgyTz5Qc2zkv9HFQrvCTO8MNjhkp6FrzqK30YIsaoV5upal6UY3/jfpvXy7Q7DWQ6uXURm5ySCDmlOSBqeCdieBtJVDwCIPBKHgfBkxu+vkMitsGgDD6P5wZ8EqSQjCXIkjk3ZJd0KnWIHmOpbCeykT4praQuuRFQWPy4kT7b+SCNImgTyl2Xo5J+QCtud0Nu6HqBYPoDELDXHhCIY6vgreWDon6XgD8E8J155rtcjU0toyFJm1u+AgmVIl81RI6Z4o/O/uM4kUGgfligHNCHiY+XJGUzFoJy4rwtuPD6fuJaGPOxdJYy/TcfrcQms0kbuULzM90btCOE2iH5BKmlQU8V0UB2nX6zUn8Vw1bMM8jlNPQ=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: btp-app
