---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affaire-service-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGODB_PASSWORD: AgAX5rYe/SJZpJpxXHXX0ynRnGpemRYFJaiGKAXB68y3GvikE1rA21WDB6AI+mEXZ2utwYTBPnhBCBLRbl4yTegwGI4Qva52pu2oEavqxlnVSRnrwpyRoQQ0gX5raFHHkHeH7xXbxe6qiqyg54IKwtlJjvORACRypN7WK4OWZESfqdpMge94lJ22dAqXo8WHv2p3Yf/VBXR+7HcOmB9ahE85ExJz4vQrcUheZPuVgnghR6DJlobTtv6skybe3pdAcMxN0AX1L/e3KZLcDCfeaO1FxwmWVdzqqYaEZex1ysInj1RnsEwL53qetTzi3DPrZurgE2sphNLK6KUCvwOD/LxfMVTZZuz/nvtEKw/Pwsd+Pz3uDW95IRW9h+R9ETwmvxl/GLjbJcXRapBFxwagDf9tlaVuW0T5LlDnWjpl2ebBuO1ZKXSJJrpUdpSQGG2rjCOb4SHHU5spcqJKLseg/KRxYuUYFIzB7UgGAi0SX/s48A6oQADbRDQvFFNIL3gsRrsQyIz7Aotv+uTtlMkQXAFVj8sulhIH6v2USBGbk+W6YFY56nGl8h8AXohAXxSKKhRoepUsgsgthO+suC7xMVVV7JiJqtSieDmiZ6gCxguKXn72tse5WLLshdyNm/M6RHmwWl+miGKRJHQHiLMg3P0VG06nEgJ+QGtqvTh4KIJFT9FV5MCxGpTyAcEZAR2EomNlfGeZ1zNdr5GM0KZJN5dysGdGNbfiVVQ=
    MONGODB_USERNAME: AgCyPoq7t2BXaQ1D0UNc9qK/yGPg2FDnFmWr8iy6mEBmOyoi/7Oq/LJy5Z5YFrOqQ8V5od/bSNp3SvcHsi5qkaW1mytZUc7Pd5WWR/R8fqw2zRy7NQgV+aRlbyIOKHhLFMDth1b6kHtvJfoGhWxJalGuDnp7HtH4DfSYHVyTgLum/qlqkHu1zOR5Gk+JXGGFqlEVB1Ww85H9w0kgwaKQ2tx4umUSPyZaA5aytjCdY9Oi79gj6hbpKvTaRmWTi311hWuP8bEanRTA+/pMMfXhANknnUX2u3BEOPlD4itAwyZQ3RqbICkRTyT8VpeVTN4TI4vmISu+unfmo6KQEX6XgVeivuYZLwwFVBF3MJC2tT9puqZH9u0AjVH9B0Uwxx2Y4K/yI9IH7OniFALabvNe9DoWyYeROnQxEUG0a9Fz9HFPu/PEMxxSKpM86Fvsw+Ve3NRWifvKXT15RNuCLNOoD4xBGbvOZr/tOvy+M0xWtXfphKSjrxOGifqA4BAoCEA9TPj4MVaOva5dNV6wmZn4UPT1YXq+qqXsPsI/1OxxvDQGucWIhccFqP7UeNwJIUY+Az5xO0D+jjgqCtGmx2I/RHoiC2gvbNV1XfYm/wS5X/kHLzNR/3QywPeRn6VQ0Yfn24WCzTiW5U6PfwwRIN/zRlrw+y6b/9TrN4qK2gznz7wDKmKQ8rWR+Omwde4I8dzKXpE4ArlFug==
  template:
    metadata:
      name: affaire-service-secret
      namespace: btp-app
