---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plan-service-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGODB_PASSWORD: AgBfSIOBAhEflJJnUlL5JRHYEZtuecWCOS/AwLa1WWgYIcGljUYrNIpyHt06GPmNK5s1G9U8WzPL8qDLAVr7YsY449gqM0iScoMeZ1GB/RVNfUrkzYALQ/xs3FJ8SoRzjcSxQKpgNRs84Utjmkn9102INGO+q/RzCr1ndNPLOExTk423vLqP+KTDPxbQRB1IXQwHAIYeqzqKYERNiNMuXdNsLfColDkGQ+S124WZCA/GDJeKci3kbliS57ExhoSkgMhNHYCDxlIJB1YlV78L9kFMZXuEkrPxT8a+t+hO6XPHzPbawQh3ip0qJlwSl/kjjgasZNTH3WROby7PvcD37bNTryR3J/SzM5PYv6zEbxNP6tyvHcsXDCJFrLaFUwmBG+S+zPFUtz0tFe61axSgDOYo+50+nR3JHoASPkfhqm90EzWB/gcMuZn9kgIC6vMqUOi57CNX68gwyNXKCiGz7QGrD30nErN/6rU/4ZcFg62FFSrVvInWacdbtstY/eE6tSjshaOw13VfKpvcsTWtoPVslpk6jauGQ5kx3hcu7P/N0d0khw7h2LxF1/FLXXRwYSWD2PwoIsUALhTu8FubzxkAsy9lEabqbIZO/3zTmtVx+3sGmmKsDi5+TffjcSlzZJV/x6TsR4ZE2OQzVhe0CK6jCPA9cmsPq8nxZn7KLpjToFv5qzKQuuqbliw2Rk7TRpeREJNApPapxMq9JYQ6XVgD09nU4Bv8SoE=
    MONGODB_USERNAME: AgATNZ6il8bq4tlaqOEX7X8GsksBIaaWht3aL+sWL1375x07xIm+Qkd80sTUj4at+x3Q9I1O0Zwrm4cxHcU8VLMX2FKLoOAMDxQ2qXVu8AFi/Jhr6KwWEzRU4jTILxehFSdPbp0CdSsSa9ODxOgAdnJarrcy9QrVkd5cfvZdkllIhDn/Mdz7e8MyAlrdvVjoj4OAdl8xaCyKbqU3iZWVibilDiaj0ROBjl0asyUb7p/QrY6GabIFqyoaqxaRS1gBQmPOO/xEJGVnNsr4mN5smbeLlAhaAJvK2UWAMJIubLm2B3PExGCPo8riWTQBUsYi9B5z/5Et2TGCZ8DSfRAOP+aM5tvM7qy8oOXSB2yrF2+yvxkjvxW0MPuTodUDXZzti8NkxQwHMyNrrqFl0uiWeYgfwqZkA7a77E1VPtZaawWUh/BkAWtefHGqUCtcukQyS1whGPDw0RJNIeLIz0/cxBz8E6xHcksHxWt6kYhTg1qKZq5D2J4YzqlYnTQ6u9KlB5vkkcTdYwMiWmu1MY9/6JmF56RApc62Xwmg8GmiXE/6B5MXcLlGDGCtUlxNjz+caOk2NHbYNi/PO/zXmJaVos+xXCLX/u3OO7085NbFVOqxmRt+jh09lDA/mJ7N3Z+oKQzUU62QqiN1foXZxyStK/m23ZdUzP0RlHQ2H15ZNIWYg4YorVjn0XS4/G7vp6FujDQn17OLnA==
  template:
    metadata:
      name: plan-service-secret
      namespace: btp-app
