---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: btp-app
spec:
  encryptedData:
    JWT_SECRET: AgCJMgmMf8FkKL5CKcwwG9EJUmP1RaJqQtYy9W/o7st0Qm49xy29jgsVcQpXKwORYlnv6WWSt7yATpZ0x2pFZhR7WmDr/LBXqH7rcxBi73iKbmtqqob74ScMBBL47sYtHjKhBTBsvK4DY+/xuQNTP3iw+GHld/eOC1jssBxX7mGW5Ft8pBQMqdxSUQLuVi8phSmCcbObe8CCSMR3EGZk/AVmkIvjOpmuFukgjAV347kBca5bdonIOw3RvjZC3KUZpvi/EW2PkxEuRGXXxFFz4A4ERLM9crbtC/diiaauFdxkbtaW8vEV8yonP7Og8jzUzlX4MHOJdKqpeT7BKC5QY7ofEkUPByyAunYu1nRtZ9kfobnzlzcnAtfEjUK66ojUx0v3iZV8jJ0+OAdHAB2yn2b2qdep+f2uL3qWmXLpb3kWxKt2B+I61EI9hYMPbP7UcvpErffWURzG9Uf7QYmYeeaMaUnZsayc9t4PpgRxse9zlA6mgbLL58EcH5oSRuDRMCGROs1zrnU4D69VruqNQgBWSo3IiZi2QdTiVdTNCjnVoc2d1NaAFvcfV94Bju/mzw1/pykrKwIT4JyBE+wksdCBTwxVg6Z0RPKRlloiyh259E4BtFZVEd7msIaEzhgA3mdON923e+46Cwe2eAuA6VmynoUQ6j8nmTSxXAYiTYjzYAlbnADhnjEa8fGqZNtEzzagn2bRvf6HcZ7KwPyHw9baIohTfifL3QdGc1tT/UcOw1LNkk6j+cbK2VlejmlZMT3L4X+shJwzBrxlF46IZ1KzzILNlK7GAiK0
  template:
    metadata:
      name: jwt-secret
      namespace: btp-app
    type: Opaque
