---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affaire-service-secret
  namespace: btp-app
spec:
  encryptedData:
    MONGODB_PASSWORD: AgA3Jy4eC+dcMLDLsZyXOOsh81t3jBvbTqjnXq3h4ESZOBGXVToenrj9F+ssuMoNSVBlflad/qVmY2f/xabNK9RGSL882ihbs6IzSutUJ7KO4FnABbncz2rgsztKY/Pgt9Avjs8+8bnCLbM/GJ08OaD5m+2jkpMP4m4dAOGOv/XRdJeIlRvX1MDGxcI/k9x3DDsnsQPL8Pdlt/sum/l5eQxKjDewMu1de8Sgnmq6OOJLcwFaC2M1kAMxzrCnwY2ojU9I2ebQQgHxNrtxQ6ExQaBD9NmReLkiAK33VRFv1+/ExUnVBOf1W9omXwQqI89JSJtt2AbFm1mR7dZM9NkGiyzmvf8NzPn5FTK5Xk9wH/Oqn06MnjGNuKoGUROSn5WrEcZYBdZ0JqxzZpLzrcVyfXhBrunJRLkfB583Znf+ZdquI/d3qPZvLLD2PFRuDVUCoFbf/UHQ/5ML5N07pTofQGGy37qgrcPNYKLHWtWD0MG7STw3FpyxzCfP/htM9mWy51/oY+Vj0asJ4/P3ozK+b1iIduSzgM2QiBvq62dv/hm0F9KJXQKqvk4Mbo452KBX7nA0ypq1LsTVxErGk0j70/r2iXNnPeD+buGPpq2zyAk8tIc3tg6yipWBJS2sZAB9v8nCrTbq2pe9VS/xX9vH4HVm+0r796ltlSLnkHj6IQGYnM+vDG06DnWY2MFLMDcWE2EXAj7DjbsJxc3oFVxv8LloanCFbGnWVek=
    MONGODB_USERNAME: AgAYQb8GvdwtRsdKTk853ZMkt2xlCKZXOlEHpcI34fajERZDjpr3WGE5RRB5N60ygQkxEjacq8Hf4uW2oq0jswDERLWHTsKFcwd+G8HcC2s6sjTKXnoEReAV3k28R6WK2DldVt+UGYTZjEVCKOJR6yHlhviOBJLWoLz2JoDQMeComuYlx5u8ZtchH2OH8ok6fNBk9G5X6f6e0aKYar07PDX3GPDKinUuOR1/W1r8QKaNt6GGEMa/Jl0agAvX6gY8GIq8un7Sw3kq79m4PqXBiSTCcCre0UIuk4pksPOoz2M4ZnwSqXephWh+h8n0vskqce0WUaqqQbR2QsBb5w+7Q2nNF4GuVMcjWMbr11evmcfplDqKK7OBFK5YqaI7WMSXq4igcw3vO3WvQSUdDkqS+q8DI7VgSkQl15kQywqc+o3Vjf+jB/3gQflEUCuEk6BUNH1SKSb2mgWFkkKrVSXPDBTS0jNc2UY3cbzVdUrhSHg4/TPEf6wzkCO/ZwLJr7lrkf43nshuRnXdzQxx4fdPrjF1XykDWuOF477UuR2QAM5XVwFMKBGSGPNOV9Lntcan66/1Jo4PNhTRwXUfxkTkH/Ak+J2yJ+qxjRC6X++AorparMYLiKWt+dBFDgtE6EX86C2a1rWdbfD4mBVwOtTA6myA2j/sTbuPiINUocSuwOUOfmxtJJIY8a5fkAocnsOaMVz6PrnKQg==
  template:
    metadata:
      name: affaire-service-secret
      namespace: btp-app
    type: Opaque
