apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Default-deny + allowlist least-privilege (réseau btp-app).
resources:
  - 00-default-deny.yaml
  - 01-allow-dns.yaml
  - 10-frontend.yaml
  - 20-api-gateway.yaml
  - 30-user-service.yaml
  - 31-affaire-service.yaml
  - 32-plan-service.yaml
  - 33-controle-service.yaml
  - 34-notification-service.yaml
  - 40-eureka-server.yaml
  - 41-mongodb.yaml
  - 42-rabbitmq.yaml
  - 43-mongodb-exporter.yaml
