---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anthropic-secret
  namespace: btp-app
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgAHLcrcnm21EwrtzbhOhXEhs6FC0l6guDJQtjZF7lFVk9k/p8RbZx9GXhZglCHZEPJqGRDaAoxs4nT+m6njgv8+/lR+ESsiMhekdILJTRBMZySWdhCFAPFGON8Yp7Nzv23oQQd5AcJaLUPHcIs/zBlf1Bc5Ftaqr5cys1UEWnVE5Mh/y7p/7798kGuRQFACmTQ3qu9cvv4ywCyMzA/xE/iwZhMYb1+jhZyg2E2nmb5S2q/x3SchDwRc7DTz6L1bN4wRMBO6EQO2irM2Z8aA6xnY6upON3YqBhgrlKIXtjV4x4QSEkTrfGj0NdY6QHCIy2fyfg7Cc38S8bYzquXRpB3MSK689Z9gvbD7fnl8+NyF6jfu3kB/cJ2A1eEkHG9YKidZS37xzcoX/LK75ByCbXqlrSqU5XZe80yB4SaXxxTDng7dBSbZ20L7JEbQj8AVCQyoxLJlnP8pikJMwuVjhcTFeBKn5hk5bsHeWn7Lgv6LaaAgC5/GP8xEvwutxiJdn9qaURUYCiqZWyOxKyRUuqFYrF41vNdYJb11rBaeIOnTLnQ05bf5ZHG0LXbOryJGww/ST8Qr00up6Zi9kv8do+hNm/lXvKEPPb1IHNlkiOF9w83bYz9x/45z3fQJKEYr1YEJWzh4FOxfV3LfLeHNbjNrvlRlrLUhRRcLza0Dol2/9I+8lwj/KCwWB8AMulQpLgm8aX01QI2a62gn9El4u3OBZ4I9zhlq9MPYtMNghShYGdP9Pg4weMjymUBAzMm1112M4k72mtiO7ZY+SjPYSqp9/StL+HITwS9LdP0uAIZp0P5P7fOxM5gW2dorcBtcQnGhm+fJ8iH77kynqPA=
  template:
    metadata:
      name: anthropic-secret
      namespace: btp-app
