apiVersion: apps/v1
kind: Deployment
metadata:
  name: controle-service
  namespace: btp-app
  labels:
    app: controle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controle-service
  template:
    metadata:
      labels:
        app: controle-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8083"
    spec:
      containers:
        - name: controle-service
          image: controle-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083

          envFrom:
            - configMapRef:
                name: controle-service-config
            - secretRef:
                name: controle-service-secret

          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DATABASE)?authSource=$(MONGODB_AUTHSOURCE)"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"