apiVersion: v1
kind: Secret
metadata:
  name: controle-service-secret
  namespace: btp-app
type: Opaque
stringData:
  MONGODB_USERNAME: admin
  MONGODB_PASSWORD: LDnNorhO2vmJYVgXUbSytJzz

  SPRING_RABBITMQ_USERNAME: btp
  SPRING_RABBITMQ_PASSWORD: JwTRWm8RHXk1gSppastotFT5