apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: btp-app
type: Opaque
stringData:
  SPRING_RABBITMQ_USERNAME: btp
  SPRING_RABBITMQ_PASSWORD: btp123
  JWT_SECRET: btp-secret-key-for-jwt-signing-must-be-at-least-256-bits-long-for-hs256