name: CD - Build Push Deploy Local

on:
  push:
    branches: [ "main" ]

jobs:
  docker-and-deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
        shell: powershell

      - name: Build user-service jar with Docker Maven
        run: |
          docker run --rm `
            -v "${{ github.workspace }}\user-service:/app" `
            -w /app `
            maven:3.9.9-eclipse-temurin-17 `
            mvn -B clean package -DskipTests
        shell: powershell

      - name: Build api-gateway jar with Docker Maven
        run: |
          docker run --rm `
            -v "${{ github.workspace }}\api-gateway:/app" `
            -w /app `
            maven:3.9.9-eclipse-temurin-17 `
            mvn -B clean package -DskipTests
        shell: powershell

      - name: Build and push user-service image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }} ./user-service
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}
        shell: powershell

      - name: Build and push api-gateway image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }} ./api-gateway
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}
        shell: powershell

      - name: Build and push frontend image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} ./frontend-angular
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
        shell: powershell

      - name: Check kubectl context
        run: kubectl config current-context
        shell: powershell

      - name: Deploy user-service
        run: |
          kubectl set image deployment/user-service user-service=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }} -n btp-app
          kubectl rollout status deployment/user-service -n btp-app --timeout=180s
        shell: powershell

      - name: Deploy api-gateway
        run: |
          kubectl set image deployment/api-gateway api-gateway=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }} -n btp-app
          kubectl rollout status deployment/api-gateway -n btp-app --timeout=180s
        shell: powershell

      - name: Deploy frontend
        run: |
          kubectl set image deployment/frontend frontend=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} -n btp-app
          kubectl rollout status deployment/frontend -n btp-app --timeout=180s
        shell: powershell